name: Generate API Test Cases

on:
  push:
    branches:
      - main

jobs:
  generate-test-cases:
    runs-on: ubuntu-latest
    environment:
      name: assertible_tool
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Test Cases
        env:
          ASSERTIBLE_API_KEY: ${{ secrets.ASSERTIBLE_API_TOKEN }}
        run: |
          curl -X POST "https://assertible.com/api/services/4ed3742c-5f92-44ec-b96f-8813fd40b3c9/tests" \
          -H "Authorization: Bearer ${{ secrets.ASSERTIBLE_API_TOKEN }}" \
          -F "api_spec=@./testfolder/openapi.json" \
          -F "assertions=auto"
