name: API Testing with Assertible

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: assertible_tool
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run Assertible tests
      run: |
        curl https://assertible.com/apis/4ed3742c-5f92-44ec-b96f-8813fd40b3c9/run?api_token=${{ secrets.ASSERTIBLE_API_TOKEN }}
