on:
  workflow_dispatch:

jobs:   
  aws-password-expiry:
    runs-on: ubuntu-latest
    environment:
      name: my-aws-dev
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        sudo apt-get install python3-setuptools
        python -m pip install requests
        python -m pip install --user awscli
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install --update
        
    - name: Get and Analyse Data for AWS  Account
      working-directory: 'testfolder'
      run : |
        bash ./get-aws-account-data.sh
        FILE_PATH="./aws-pdata.txt"
        if [[ -z $(grep '[^[:space:]]' ./interCA-aws-pdata.txt) ]] ; then
          echo "There was no users for initimation"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-northeast-1
        
