on: push

jobs:
  secret-generator:
    runs-on: ubuntu-latest
    steps:
    - name: generate secret
      shell: bash
      run: |
        SECRET_HANDLE="Tfyscaf23"
        echo "$SECRET_HANDLE" >> "$GITHUB_OUTPUT"
  secret-consumer:
    runs-on: ubuntu-latest
    needs: secret-generator
    steps:
    - name: use secret
      shell: bash
      run: |
        SECRET_HANDLE="${{ needs.secret-generator.outputs.handle }}"
        echo "We retrieved our masked secret: $SECRET_HANDLE"
