on:
  workflow_dispatch:

jobs:   
  secret-generator:
    runs-on: ubuntu-latest
    
    outputs:
      acmpcaquota: ${{ steps.get-run.outputs.quotavalue }}
      myoutput: ${{ steps.get-run.outputs.myvalue }}
    steps:
    - uses: actions/checkout@v1 
    - name: generate secret
      id: get-run
      working-directory: 'testfolder'
      run : |
        bash ./test.sh
      
  secret-consumer:
    runs-on: ubuntu-latest
    
    needs: secret-generator
    steps:
    - uses: actions/checkout@v1        
    - name: use secret
      working-directory: 'testfolder'
      run : |
        echo ${{need.secret-generator.outputs.myoutput }}
        echo ${{ needs.secret-generator.outputs.acmpcaquota }}
        
        
