on: push

jobs:
  secret-generator:
    outputs:
      acmpcaquota: ${{ steps.get-run.outputs.acmpcaquota }}
    runs-on: ubuntu-latest
    steps:
    - name: generate secret
      shell: bash
      id: get-run
      run : |
        bash ./test.sh
      
  secret-consumer:
    runs-on: ubuntu-latest
    needs: secret-generator
    steps:
    - name: use secret
      run : |
        echo ${{ needs.secret-generator.outputs.acmpcaquota }}
        
