on:
  workflow_dispatch:

jobs:   
  secret-generator:
    runs-on: ubuntu-latest
    
    outputs:
      acicvalue: ${{ steps.get-run.outputs.acic }}
      gsaqvalue: ${{ steps.get-run.outputs.gsaq }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: generate secret
      id: get-run
      working-directory: 'testfolder'
      run : |
        bash ./test.sh
      
  secret-consumer:
    runs-on: ubuntu-latest
    
    needs: secret-generator
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
      with:
        fetch-depth: 0   
        
    - name: Install dependencies
      run: |
        sudo apt-get install python3-setuptools
        python -m pip install requests
      
    - name: use secret
      working-directory: 'testfolder'
      run : |
        echo ${{ needs.secret-generator.outputs.acicvalue }}
        echo ${{ needs.secret-generator.outputs.gsaqvalue }}
        acicvalue= ${{ needs.secret-generator.outputs.acicvalue }}
        gsaqvalue = ${{ needs.secret-generator.outputs.gsaqvalue }}
        TitleMessage="aws_accouhcsvj"
        Testvalue="gvach"
        python ./test.py ${acicvalue} ${gsaqvalue} {TitleMessage} ${Testvalue}
        
        
