on:
  workflow_dispatch:

jobs:   
  secret-generator:
    runs-on: ubuntu-latest
    
    outputs:
      acmpcaquota: ${{ steps.get-run.outputs.quotavalue }}
      myoutput: ${{ steps.get-run.outputs.myvalue }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: generate secret
      id: get-run
      working-directory: 'testfolder'
      run : |
        bash ./test.sh
      
  secret-consumer:
    runs-on: ubuntu-latest
    
    needs: secret-generator
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
      with:
        fetch-depth: 0   
        
    - name: Install dependencies
      run: |
        sudo apt-get install python3-setuptools
        python -m pip install requests
      
    - name: use secret
      working-directory: 'testfolder'
      run : |
        ACMPCADATA=${{ needs.interca_dev_check.outputs.acmpcaquota }}
        TitleMessage="aws_accouhcsvj"
        Testvalue="gvach"
        python ./test.py ${ACMPCADATA} ${TitleMessage} ${Testvalue}
        
        
