on: push

jobs:
  secret-generator:
    outputs:
      acmpcaquota: ${{ steps.get-run.outputs.acmpcaquotalimit }}
    runs-on: ubuntu-latest
    steps:
    - name: generate secret
      shell: bash
      id: get-run
      run : |
        sudo apt-get install python3-setuptools
        python -m pip install requests
        SECRET_HANDLE="Tfyscaf2345"
        echo "acmpcaquotalimit=$SECRET_HANDLE"
      
  secret-consumer:
    runs-on: ubuntu-latest
    needs: secret-generator
    steps:
    - name: use secret
      run : |
        echo ${{ needs.secret-generator.outputs.acmpcaquota }}
        
