name: Copy File Between Branches

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source branch
      uses: actions/checkout@v2
      with:
        ref: 'feat/test-main'  # Replace with the branch from where you want to copy the file

    - name: Copy file to destination branch
      run: |
        mv ./opsjob/SO_Outputs.csv ./opsjob/SO_Outputs.csv  # Adjust the file paths accordingly

    - name: Commit and push changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        echo "1,ChipID-0001,2024-02-02,1" > ./opsjob/SO_Outputs.csv;
        echo "2,ChipID-0001,2024-02-02,1" > ./opsjob/SO_Outputs.csv;
        git add ./opsjob/SO_Outputs.csv 
        git commit -m "Copy file from source_branch to destination_branch"
        git push origin main
