name: Copy File Between Branches

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check For feat branch
      run: |
        GITHUB_REPOSITORY="upendraddev/azuredev"
        branch="feat/test-main2"
        REPO_API="https://api.github.com/repos/${GITHUB_REPOSITORY}/branches/${branch}"
        response=$(curl -s -o /dev/null -w "%{http_code}" ${REPO_API})
        if [ $response != 200 ]; then
        git checkout -b ${branch}
        git push origin ${branch}
        fi

    - name: Check For Artifact file in feat branch
      run: |
        if [[ -z "./opsjob/SO_Outputs.csv" ]]; then
        echo "S.no","ChipID","Date","RequestedCount" > ./opsjob/SO_Outputs.csv;
        fi
        

    - name: Commit and push changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        echo "1,ChipID-0002,2024-02-02,1" >> ./opsjob/SO_Outputs.csv;
        echo "2,ChipID-0003,2024-02-02,1" >> ./opsjob/SO_Outputs.csv;
        git add ./opsjob/SO_Outputs.csv 
        git commit -m "Copy file from source_branch to destination_branch"
        git push origin feat/test-main
