name: Pass File Content Between Jobs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      file_content: ${{ steps.store_file_content.outputs.file_content }}  # Output from the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Read file content
        id: store_file_content
        run: |
          # Read the file content into a variable
          echo "FILE_CONTENT=$(cat ./testfolder/samplefile.txt)" >> $GITHUB_ENV 
          
          # Set the file content as an output of this step
          # echo "::set-output name=file_content::$FILE_CONTENT"

  job2:
    needs: job1  # Ensure this job runs after job1
    runs-on: ubuntu-latest
    steps:
      - name: Use file content from job1
        run: |
          # Access the file content from job1 output
          $FILE_CONTENT> sessiontoken.json
           cat sessiontoken.json
           echo $FILE_CONTENT
          # echo "File content from job1: ${{ needs.job1.outputs.file_content }}"
