name: Pass File Content Between Jobs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.session_token.outputs.sessiontoken }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          sudo apt-get install python3-setuptools
          python -m pip install --upgrade pip
          pip install fpdf
        
      - name: Read file content
        id: session_token
        run: |
          # Read the file content into a variable
          echo "sessiontoken=$(cat ./testfolder/samplefile.txt) " >> "$GITHUB_OUTPUT"

  job2:
    needs: job1  # Ensure this job runs after job1
    runs-on: ubuntu-latest
    steps:
        - run: |
                token=${{needs.job1.outputs.output1}} > sessiontoken.txt
                cat sessiontoken.txt

