name: Pass File Content Between Jobs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.sessiontoken.outputs.sessiontoken }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Read file content
        id: store_file_content
        run: |
          # Read the file content into a variable
          # cat ./testfolder/samplefile.txt > $GITHUB_WORKSPACE/Sessiontoken.json
          echo "sessiontoken=$(cat ./testfolder/samplefile.txt) " >> "$GITHUB_OUTPUT"
          ls $GITHUB_WORKSPACE
          # FILE_CONTENT=$(cat ./testfolder/samplefile.txt)
          # echo "FILE_CONTENT=$FILE_CONTENT" >> $GITHUB_ENV
          # # Set the file content as an output of this step
          # # echo "::set-output name=file_content::$FILE_CONTENT"

  job2:
    needs: job1  # Ensure this job runs after job1
    runs-on: ubuntu-latest
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1"
