name: Test Random Exit Codes with Retry

on:
  workflow_dispatch:

jobs:
  test-random-exit:
    runs-on: ubuntu-latest
    steps:
      - name: Retry sudo commands with random exit codes
        run: |
          # Enable script to continue on errors
          set +e
          # Define the maximum number of retries and delay between attempts
          MAX_RETRIES=5
          DELAY=10
          # Retry logic using a for loop
          for ((i=1; i<=MAX_RETRIES; i++)); do
            echo "Attempt $i..."
            # Simulate a random sudo command that might fail
            echo "Simulating sudo command with exit code $RANDOM_EXIT_CODE"
            sudo apt-get update
            RANDOM_EXIT_CODE=1
            # sudo apt install firefox -y 
            python -m pip install --upgrade pip 
            pip install -r requirement.txt 
            sudo pip install html-testRunner
            python -m pip install -U selenium==4.12.0 
            # Run the command
            sudo bash -c "exit $RANDOM_EXIT_CODE"
            EXIT_CODE=$?
            if [ $EXIT_CODE -eq 0 ]; then
              echo "Command succeeded on attempt $i!"
              break
            else
              echo "Command failed with exit code $EXIT_CODE. Retrying..."
            fi
            sleep $DELAY
          done
            # Print final status
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Command did not succeed after $MAX_RETRIES attempts"
            exit 1
          else
            echo "Command succeeded!"
          fi

