name: Test Random Exit Codes with Retry

on:
  workflow_dispatch:

jobs:
  test-random-exit:
    runs-on: ubuntu-latest
    steps:
      - name: Retry sudo commands with random exit codes
        run: |
          # Enable script to continue on errors
          set +e
          # Retry logic using a for loop
          for ((i=1; i<=5; i++)); do
            echo "Attempt $i..."
            # Simulate a random sudo command that might fail
            RANDOM_EXIT_CODE=$((RANDOM % 2))
            echo "Simulating sudo command with exit code $RANDOM_EXIT_CODE"
            sudo apt-get update
            sudo apt install firefox -y 
            python -m pip install --upgrade pip 
            pip install -r requirement.txt 
            sudo pip install html-testRunner
            python -m pip install -U selenium==4.12.0 
            # Run the command
            sudo bash -c "exit $RANDOM_EXIT_CODE"
            EXIT_CODE=$?
            if [[ $i -lt 5 ]] || [[ $EXIT_CODE -ne 0 ]]; then
              sleep 10
            else
              echo "Command did not succeed after 5 attempts"
              exit 1
            fi
          done

