name: Test Random Exit Codes with Retry

on:
  workflow_dispatch:

jobs:
  test-random-exit:
    runs-on: ubuntu-latest
    steps:
      - name: Retry sudo commands with random exit codes
        run: |
          # Enable script to continue on errors
          set +e
          
          # Define the maximum number of retries and delay between attempts
          MAX_RETRIES=5
          DELAY=2
          
          # Retry logic using a for loop
          for ((i=1; i<=MAX_RETRIES; i++)); do
            echo "Attempt $i..."
            # Simulate a random sudo command that might fail
            RANDOM_EXIT_CODE=$((RANDOM % 2))
            echo "Simulating sudo command with exit code $RANDOM_EXIT_CODE"
            sudo apt-get update 
            sudo apt install firefox -y 
            python -m pip install --upgrade pip 
            pip install -r requirement.txt 
            sudo pip install html-testRunner
            python -m pip install -U selenium==4.12.0 
            # Run the command
            sudo bash -c "exit $RANDOM_EXIT_CODE"
            break
            EXIT_CODE=$?
            echo "Exitcode: $EXIT_CODE"
            [[ $i -lt 5 ]] && sleep 10 || { echo "Max retries reached. Exiting..."; exit 1; }
            echo "Exitcode: $EXIT_CODE"
          done
