name: Test Random Exit Codes with Retry

on:
  workflow_dispatch:

jobs:
  test-random-exit:
    runs-on: ubuntu-latest
    steps:
      - name: Retry sudo commands with random exit codes
        run: |
          # Define the maximum number of retries and delay between attempts
          MAX_RETRIES=5
          DELAY=2
          
          # Retry logic using a for loop
          for ((i=1; i<=MAX_RETRIES; i++)); do
            echo "Attempt $i..."
            
            # Simulate a random sudo command that might fail
            RANDOM_EXIT_CODE=$((RANDOM % 2))
            echo "Simulating sudo command with exit code $RANDOM_EXIT_CODE"
            
            # Run the command and capture the exit code
            sudo bash -c "exit $RANDOM_EXIT_CODE"
            EXIT_CODE=$?
            
            if [ $EXIT_CODE -eq 0 ]; then
              echo "Command succeeded on attempt $i!"
              break
            else
              echo "Command failed with exit code $EXIT_CODE. Retrying..."
            fi
            
            # If we've reached the maximum retries, fail the job
            if [ $i -eq $MAX_RETRIES ]; then
              echo "Max retries reached. Failing the job."
              exit 1
            fi
            
            # Wait before the next attempt
            sleep $DELAY
          done
