name: Python CI with Retry

on:
  push:
    branches:
      - main

jobs:
  setup-python-with-retry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Retry Setup Python
      working-directory: ./opsjob/scripts
      run: |
          sudo add-apt-repository ppa:mozillateam/ppa -y
          echo '
          Package: *
          Pin: release o=LP-PPA-mozillateam
          Pin-Priority: 1001
          ' | sudo tee /etc/apt/preferences.d/mozilla-firefox
          echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
          max_retries=3
          retry_count=0
          while [ $retry_count -lt $max_retries ]; do
              sudo apt-get update && sudo apt install firefox -y && python -m pip install --upgrade pip && python -m pip install -U selenium==4.12.0 && break
              retry_count=$((retry_count + 1))
              echo "Retrying commands... ($retry_count/$max_retries)"
              sleep 2
          done

          if [ $retry_count -eq $max_retries ]; then
              echo "Commands failed after $max_retries retries."
          fi
          # for i in {1..3}; do
          #   echo "Attempt $i to setup Python"
          #   if sudo apt-get update; sudo apt install firefox -y; python -m pip install --upgrade pip; then
          #     echo "Python setup succeeded!"
          #     break
          #   elif [ $i -eq 3 ]; then
          #     echo "Python setup failed after $i attempts. Exiting."
          #     exit 1
          #   fi
          #   sleep 10
          # done
          # python -m pip install -U selenium==4.12.0
