name: Sync File to Other Repo

on:
  push:
    branches:
      - main
    paths:
      - 'testfolder/samplefile.txt'  # Change this to the file you want to sync

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Clone target repository
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone https://github.com/upendraddev/azuredev2.git target-repo
          cd target-repo
          git checkout -b sync-file-update
          git config user.email "upendrad.dev@gmail.com"
          git config user.name "upendraddev"

      - name: Copy the updated file
        run: |
          ls -la
          pwd
          cp testfolder/samplefile.txt target-repo/
          cd target-repo
          git add samplefile.txt
          git commit -m "Sync file update from source repo"
          git push origin sync-file-update

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: upendraddev/azuredev2
          branch: sync-file-update
          base: main
          title: "Sync file update from source repo"
          body: "Automated PR to sync file updates from the source repository."
          commit-message: "Sync file update from source repo"
