name: retrieve all run ids
on:
  workflow_dispatch:

jobs:   
  ssla-certs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  
    - name: Script Execution For Certificate Operations
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash ./testfolder/retrieve_runids.sh \