name: Upload and Download Artifacts with Retry

on:
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate a sample file
      - name: Create Sample File
        run: |
          mkdir -p output
          echo "This is a sample file" > output/sample.txt

      # Step 2: Upload the artifact
      - name: Upload Sample Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sample-artifact
          path: output/

  download-artifact:
    needs: upload-artifact
    runs-on: ubuntu-latest
    steps:
      # Step 1: Retry logic for downloading artifact
      - name: Download Artifacts with Retry
        id: retry_download
        run: |
          set -e
          MAX_RETRIES=5
          RETRY_DELAY=10
          retry_count=0

          while [ $retry_count -lt $MAX_RETRIES ]; do
            echo "Attempt $((retry_count + 1)) to download artifacts..."
            gh artifact download --name sample-artifact || true

            # Check if the artifact folder exists and is not empty
            if [ -d "my-artifact-name" ] && [ "$(ls -A my-artifact-name)" ]; then
              echo "Artifacts downloaded successfully on attempt $((retry_count + 1))"
              break
            fi

