name: dependency management maintenance
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  workflow-start:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        msvcode: ["labff", "ladps"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: CI
        run: |
           MSV_CODE="${{ matrix.msvcode }}"
