name: test-ssla-certs2
on:
  workflow_dispatch:
    inputs:
      chipIds:
        description: 'Specify the ChipID'
        required: true
  # push:
  #   branches:
  #     - main

jobs:   
  ssla-certs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  

    # - name: Install dependencies
    #   run: |
    #     sudo apt-get install python3-setuptools

    - name: Download Previous Execution Artificats.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        OTHER_REPO="upendraddev/azuredev"
        WF_NAME="test-ssla-certs2.yml"
        ARTIFACT_NAME="Test"
        RUNS=$(curl -s -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer $GITHUB_TOKEN" \
        "https://api.github.com/repos/$OTHER_REPO/actions/workflows/$WF_NAME/runs")
        RUN_ID=$(echo "$RUNS" | jq -r '.workflow_runs[1].id')
        if [[ "$RUN_ID" == "null" ]];  then 
        echo "iamm  null"
        else
        # echo "$RUN_ID HEllo I am not null"
        API_URL="https://api.github.com/repos/${OTHER_REPO}/actions/runs/${RUN_ID}/artifacts"
        response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" $API_URL)
        artifact_id=$(echo "$response" | jq -r ".artifacts[] | select(.name == \"$ARTIFACT_NAME\") | .id")
        echo "$artifact_id"
        fi