name: Display File Content in Workflow

on:
  workflow_dispatch:

jobs:
  display-file-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read file content and set as environment variable
        run: |
          FILE_CONTENT=$(cat testfolder/samplefile.txt)
          echo "FILE_CONTENT=${FILE_CONTENT}" >> $GITHUB_ENV

      - name: Display file content
        run: echo "$FILE_CONTENT"
