name: Display File Content in Workflow

on:
  workflow_dispatch:

jobs:
  display-file-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - uses: actions/upload-artifact@v3
        with:
          name: SESSION TOKEN CONTENT
          path: |
            ./testfolder/samplefile.txt
