name: Display File Content in Workflow

on:
  workflow_dispatch:

jobs:
  display-file-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run E2E Test Pre conditions
        id: pre-conditions
        run: |
          echo "Run E2E Test Pre conditions"
          exit 1  # Simulating failure
          
      - name: Run E2E Test
        id: main
        run: |
          echo "Run E2E Test"
          exit 1  # Simulating failure
          
      - uses: actions/upload-artifact@v4
        if: ${{ steps.main.conclusion == 'failure' || steps.pre-conditions.conclusion == 'failure' }}
        with:
          name: SESSION TOKEN CONTENT
          path: ./testfolder/samplefile.txt
