name: retrieve all run ids
on:
  workflow_dispatch:

jobs:   
  ssla-certs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  


    # - name: Retrive runid
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     bash ./testfolder/retrieve_runids.sh \

    - name: Retrive artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash ./testfolder/retrieve_artifacts.sh \