name: Run OPA Tests
on: [push]
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        msvcode: ["labff"]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - uses: actions/setup-go@v3
      with:
        go-version: 1.21.0
        
    - name: CI
      run: |
        MSV_CODE="${{ matrix.msvcode }}"
        bash ./testfolder/vulnerability-scan.sh \
          ${MSV_CODE} 
