name: Display File Content in Workflow

on:
  workflow_dispatch:

jobs:
  display-file-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run E2E Test Pre conditions
        id: pre-conditions
          echo "This is E2E Test conditions"
          exit 1 
          
      - name: Run E2E Test
        id: main
          echo "This is E2E Test"
          exit 1 
          
      - uses: actions/upload-artifact@v4
        if: ${{ steps.pre-conditions.conclusion == 'failure'  && steps.main.conclusion == 'failure'  }}
        with:
          name: SESSION TOKEN CONTENT
          path: ./testfolder/samplefile.txt
