name: test-ssla-certs2
on:
  workflow_dispatch:
    inputs:
      chipIds:
        description: 'Specify the ChipID'
        required: true
  # push:
  #   branches:
  #     - main

jobs:   
  ssla-certs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  

    # - name: Install dependencies
    #   run: |
    #     sudo apt-get install python3-setuptools

    - name: Download Previous Execution Artificats.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        OTHER_REPO="upendraddev/azuredev"
        WF_NAME="test-ssla-certs2.yml"
        ARTIFACT_NAME="Test"
        TOTAL_RUNS=$(gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId | jq '. | length')
        if [[  $TOTAL_RUNS == 1 ]]; then 
        # echo "S.no,ChipID,Date,Requested Count" 
        else
        # echo "HEllo Run idd"
        RUN_ID=$(gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[1].databaseId)
        # echo "$RUN_ID"
        gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME}
        fi

        # gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME}
        # filecount=$(ls | grep .csv -c)
        # echo "$filecount"
        # if [[  $filecount == 1 ]]; then 
        #   filename=$(ls | grep .csv )          
        #   # cp $filename ./microservices/opsjob/
        # fi