name: test-ssla-certs
on:
  workflow_dispatch:

jobs:   
  ssla-certs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Script Execution For Certificate Operations
      run: |
          sudo apt install pwgen -y
          ChipIDCount="2"
          PASSPHRASE=$(pwgen 12 1)
          timestamp=$(date +%Y%m%d%H%M%S)
          cd testfolder/testssl/
          echo "Pass Phrase"::${PASSPHRASE} >>./password.txt
          echo "ChipID" > ./test-gen.csv; \
          echo "Sid-001" >> ./test-gen.csv
          sudo apt install p7zip-full -y
          7za a -tzip -p${PASSPHRASE} -mem=AES256 SOFiles.zip SOFiles
    - uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: SOFiles
        path: |
          ./testfolder/testssl/password.txt
          ./testfolder/testssl/test-gen.csv
          ./testfolder/testssl/SOFiles.zip
          
