name: test-ssla-certs
on:
  workflow_dispatch:

jobs:   
  ssla-certs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Script Execution For Certificate Operations
      run: |
          sudo apt install pwgen -y
          ChipIDCount="2"
          ChipID="Test-998"
          PASSPHRASE=$(pwgen 12 1)
          certificate_pem="Testcertd"
          timestamp=$(date +%Y%m%d%H%M%S)
          dir=${timestamp}-SOFiles 
          mkdir -p ./testfolder/testssl/${dir}
          bash ./testfolder/testssl.sh \
          "$ChipID" \
          "$dir"
          cd testfolder/testssl/
          echo "Pass Phrase"::${PASSPHRASE} >>./password.txt
          echo "ChipID" > ./test-gen.csv; \
          echo "Sid-001" >> ./test-gen.csv
          sudo apt install p7zip-full -y
          7za a -tzip -p${PASSPHRASE} -mem=AES256 ${timestamp}-SOFiles.zip ${timestamp}-SOFiles
    - uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: SOFiles
        path: |
          ./testfolder/testssl/*
          
    - name: Download Previous Execution Artificats.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          OTHER_REPO="/azuredev"
          WF_NAME="test-ssla-certs.yml"
          ARTIFACT_NAME="SOFiles"
          RUN_ID=$(gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[1].databaseId)
          gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME}
          if [[ -f "./utils/OffsetForMFRAndModelIndex.csv" ]]; then
            cp ./testfolder/testssl/test-gen.csv ./testfolder/utils
          fi

          
