name: Display File Content in Workflow

on:
  workflow_dispatch:

jobs:
  display-file-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read file content and set as environment variable
        run: |
           bash ./testfolder/test.sh

      - name: Display file content
        run: echo "$FILE_CONTENT"
