name: Upload Artifacts on Failure

on:
  workflow_dispatch:

jobs:
  job_a:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4
      
      - name: Step 2 - Run something that may fail
        id: run_may_fail
        run: |
          # Simulate failure
          exit 1
          
      - name: Step 3 - Run something that may fail
        id: run_may
        run: |
          # Simulate failure
          exit 0

      - name: Upload logs (optional - if you want to upload in the same job)
        if:  ${{failure()}}
        uses: actions/upload-artifact@v4
        with:
          name: SESSION TOKEN CONTENT
          path: ./testfolder/samplefile.txt

  # upload_artifact_on_failure:
  #   needs: job_a
  #   runs-on: ubuntu-latest

  #   # This job runs only if job_a has failed
  #   if: ${{ failure() }}

  #   steps:
  #     - name: Download logs from previous job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: SESSION TOKEN CONTENT
